name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write  # For trusted publishing to PyPI

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Check package
      run: python -m twine check dist/*
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
    
    - name: Get version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Generate changelog
      id: changelog
      run: |
        if git describe --tags --abbrev=0 HEAD^ >/dev/null 2>&1; then
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^)
          echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
          
          # Generate changelog
          {
            echo "CHANGELOG<<EOF"
            echo "## 🚀 What's Changed"
            echo ""
            git log ${PREVIOUS_TAG}..HEAD --pretty=format:"- %s" --no-merges
            echo ""
            echo ""
            echo "**Full Changelog**: https://github.com/${{ github.repository }}/compare/${PREVIOUS_TAG}...v${{ steps.version.outputs.VERSION }}"
            echo "EOF"
          } >> $GITHUB_OUTPUT
        else
          echo "CHANGELOG=Initial release" >> $GITHUB_OUTPUT
        fi
    
    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: Token Counter CLI v${{ steps.version.outputs.VERSION }}
        body: |
          ## 📦 Token Counter CLI v${{ steps.version.outputs.VERSION }}
          
          ${{ steps.changelog.outputs.CHANGELOG }}
          
          ## 📦 Installation
          ```bash
          pip install token-counter-cli
          ```
          
          ## 🔗 Links
          - **PyPI Package**: https://pypi.org/project/token-counter-cli/${{ steps.version.outputs.VERSION }}/
          - **Documentation**: See README.md for full usage guide
        artifacts: "dist/*"
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }} 